alter table public.stock_movements drop constraint if exists stock_movements_movement_type_check;
alter table public.stock_movements add constraint stock_movements_movement_type_check check (movement_type = any (array['entry','exit','transfer_to_prospecteur','return_from_prospecteur','sale','adjustment','loss','transfer_out','transfer_in']::text[]));
create index if not exists idx_jdvcrm_stock_movements_org_article_created on public.stock_movements(organization_id,article_id,created_at desc);
create index if not exists idx_jdvcrm_stock_movements_reference on public.stock_movements(reference_type,reference_id,article_id,movement_type);
create index if not exists idx_jdvcrm_stock_movements_prospecteur on public.stock_movements(organization_id,prospecteur_id,created_at desc) where prospecteur_id is not null;
create index if not exists idx_jdvcrm_stocks_org_article on public.stocks(organization_id,article_id);
create index if not exists idx_jdvcrm_prospecteur_stocks_org_prospecteur on public.prospecteur_stocks(organization_id,prospecteur_id);
alter table public.stocks enable row level security;
alter table public.stock_movements enable row level security;
alter table public.prospecteur_stocks enable row level security;
drop policy if exists jdvcrm_stocks_admin_all on public.stocks;
create policy jdvcrm_stocks_admin_all on public.stocks for all to authenticated using (private.is_super_admin() or private.is_org_admin(organization_id)) with check (private.is_super_admin() or private.is_org_admin(organization_id));
drop policy if exists jdvcrm_stock_movements_admin_all on public.stock_movements;
create policy jdvcrm_stock_movements_admin_all on public.stock_movements for all to authenticated using (private.is_super_admin() or private.is_org_admin(organization_id)) with check (private.is_super_admin() or private.is_org_admin(organization_id));
drop policy if exists jdvcrm_stock_movements_prospecteur_select on public.stock_movements;
create policy jdvcrm_stock_movements_prospecteur_select on public.stock_movements for select to authenticated using (prospecteur_id is not null and private.is_prospecteur(organization_id) and exists (select 1 from public.prospecteurs p where p.id=stock_movements.prospecteur_id and p.user_id=auth.uid() and p.organization_id=stock_movements.organization_id));
drop policy if exists jdvcrm_prospecteur_stocks_admin_all on public.prospecteur_stocks;
create policy jdvcrm_prospecteur_stocks_admin_all on public.prospecteur_stocks for all to authenticated using (private.is_super_admin() or private.is_org_admin(organization_id)) with check (private.is_super_admin() or private.is_org_admin(organization_id));
drop policy if exists jdvcrm_prospecteur_stocks_own_select on public.prospecteur_stocks;
create policy jdvcrm_prospecteur_stocks_own_select on public.prospecteur_stocks for select to authenticated using (private.is_prospecteur(organization_id) and exists (select 1 from public.prospecteurs p where p.id=prospecteur_stocks.prospecteur_id and p.user_id=auth.uid() and p.organization_id=prospecteur_stocks.organization_id));
