insert into public.ai_jdv_knowledge (scope,topic,content,active)
values
('module','dashboard','Le tableau de bord est le point de pilotage : il sert à comprendre la situation avant d agir. L assistant doit orienter vers les indicateurs, alertes et modules opérationnels pertinents selon le rôle.','true'),
('module','sous_entrepots','Les sous-entrepôts sont des unités opérationnelles rattachées à un entrepôt parent. L administrateur peut les créer, leur attribuer un code, une zone et un responsable. Leur stock, journal et clôture restent liés au périmètre de l entrepôt parent.','true'),
('module','journal_stock','Le journal de stock sert à retracer les mouvements avec date, heure, article, emplacement, type de mouvement, quantités et valeurs. Il répond à la question : qui a fait quoi, quand et sur quel stock ?','true'),
('module','cloture_stock','La clôture journalière compare le stock théorique au contrôle physique, calcule les écarts et conserve une trace de validation. Elle vient après les mouvements et le contrôle d inventaire.','true'),
('module','prospecteurs','Le module prospecteurs sert à organiser la prospection terrain, suivre les agents, les prospects et la progression vers le client puis la vente. L assistant doit distinguer prospecteur, commercial, superviseur et administrateur selon les droits.','true'),
('module','retours','Un retour de marchandise doit être traçable avec l agent ou prospecteur, la date et l heure, le code article, la quantité, l emplacement, le motif, une référence de retour et le statut. Le retour doit être réceptionné et contrôlé avant réintégration définitive au stock.','true'),
('module','articles_admin','Lorsqu un administrateur crée un article, l assistant doit l aider à choisir un code unique, un nom clair, une catégorie, une unité et les informations métier utiles au secteur. Il ne doit jamais inventer une caractéristique technique absente.','true'),
('module','vente_vers_stock','Le parcours métier conseillé est : article correctement configuré -> prospect ou client -> vente -> sortie de stock -> paiement ou suivi du paiement -> retour éventuel -> contrôle et reporting. Chaque transition doit expliquer pourquoi l étape suivante dépend de la précédente.','true'),
('module','approvisionnement','L approvisionnement commence par le besoin, passe par la demande et le fournisseur, puis la réception. La réception validée doit alimenter la traçabilité du stock selon les règles du CRM.','true'),
('module','tracabilite','La traçabilité relie les opérations à leur auteur, leur date et leur emplacement. Elle doit permettre de reconstituer les mouvements, retours, inventaires et clôtures sans mélanger les organisations.','true'),
('module','administration','Les fonctions d administration couvrent l organisation, les utilisateurs, rôles, permissions, entrepôts, sous-entrepôts, catalogue et pilotage. Toute action sensible doit rester soumise aux permissions serveur et ne doit jamais être exécutée uniquement sur instruction de l IA.','true')
on conflict (scope,topic) do update set content=excluded.content, active=true, updated_at=now();