-- JDV CRM migration history checkpoint
-- Remote Supabase project arxhppptxeeyeexkdyjv has this migration recorded as applied.
-- historical production feature migration already applied remotely; checkpoint only
-- This file intentionally performs no SQL so migration history can be tracked without replaying production changes.
